In [4]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation, PCA, NMF
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import LatentDirichletAllocation

In [5]:
complete_dataset = pd.read_csv('complete_dataset.csv')
df = complete_dataset.head(10000)
print(df)
#comments = comments.head(10000) #first 3000 comments
#print(comments)
#type(comments)

      professor_name                                 school_name  \
0     Leslie  Looney  University Of Illinois at Urbana-Champaign   
1     Leslie  Looney  University Of Illinois at Urbana-Champaign   
2     Leslie  Looney  University Of Illinois at Urbana-Champaign   
3     Leslie  Looney  University Of Illinois at Urbana-Champaign   
4     Leslie  Looney  University Of Illinois at Urbana-Champaign   
...              ...                                         ...   
9995    Jamie  Mills                       University of Alabama   
9996    Jamie  Mills                       University of Alabama   
9997    Jamie  Mills                       University of Alabama   
9998    Jamie  Mills                       University of Alabama   
9999    Jamie  Mills                       University of Alabama   

           department_name                    local_name state_name  \
0     Astronomy department   Champaign\xe2\x80\x93Urbana         IL   
1     Astronomy department   Champaign\xe

In [6]:
comments_list = comments.tolist()
comments_list = [doc if isinstance(doc, str) else '' for doc in comments_list]
type(comments_list)
#print(comments_list)

NameError: name 'comments' is not defined

In [16]:
vectorizer = CountVectorizer(max_features=500, stop_words='english') #max_df=0.5, min_df=5
bow_model = vectorizer.fit_transform(comments_list)
#print(bow_model)
#type(bow_model)
#print(bow_model.shape)
arr = bow_model.toarray()
print(arr.shape)


(10000, 500)


In [7]:
data = pd.read_csv('bagOfWords.csv_1000')
print(data)
X = data.values
print(data.columns)

      hard  twoinone  gened  knockout  content  stimulating  unlike  actually  \
0        1         1      1         1        1            1       1         1   
1        0         0      0         0        0            0       0         0   
2        0         0      0         0        0            0       0         0   
3        0         0      0         0        1            0       0         0   
4        0         0      0         0        0            0       0         0   
...    ...       ...    ...       ...      ...          ...     ...       ...   
9995     1         0      0         0        0            0       0         0   
9996     0         0      0         0        0            0       0         0   
9997     1         0      0         0        0            0       0         0   
9998     0         0      0         0        0            0       0         0   
9999     0         0      0         0        0            0       0         0   

      participate  pas  ...

In [8]:
lda_model = LatentDirichletAllocation(n_components = 5, random_state = 42)
lda_topics = lda_model.fit_transform(X)

In [9]:
lda_model.perplexity(X, sub_sampling=False) # perplexity


1678.9234897595188

In [10]:
lda_model.score(X, y=None)   #log-likelihood


-1148364.7043141893

In [27]:
from gensim.models import CoherenceModel
import gensim.corpora as corpora

def get_Cv(model, df_columnm):
  topics = model.components_

  n_top_words = 20
  texts = [[word for word in doc.split()] for doc in df_columnm]

  # create the dictionary
  dictionary = corpora.Dictionary(texts)
  # Create a gensim dictionary from the word count matrix

  # Create a gensim corpus from the word count matrix
  corpus = [dictionary.doc2bow(text) for text in texts]

  feature_names = [dictionary[i] for i in range(len(dictionary))]

  # Get the top words for each topic from the components_ attribute
  top_words = []
  for topic in topics:
      top_words.append([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]])

  coherence_model = CoherenceModel(topics=top_words, texts=texts, dictionary=dictionary, coherence='c_v')
  coherence = coherence_model.get_coherence()
  return coherence

cv = get_Cv(lda_model, comments_list)
print(cv)

0.404819080541836


In [12]:
nmf_model = NMF(n_components=5, init='random', random_state=42, max_iter=500000)
W = nmf_model.fit(X)
H = nmf_model.components_
DTM = nmf_model.fit_transform(X)
print(DTM)

[[0.0271003  0.00427954 0.0015019  0.02733235 0.06863748]
 [0.01871047 0.00733748 0.02268759 0.02113161 0.07358645]
 [0.01629305 0.         0.0497529  0.02614877 0.00458157]
 ...
 [0.04871682 0.0871678  0.00013674 0.08731778 0.07139845]
 [0.03879975 0.02877551 0.01816265 0.03402191 0.        ]
 [0.01438429 0.00354968 0.         0.05478452 0.00695024]]


In [13]:
nmf_model.perplexity(X, sub_sampling=False) # perplexity


AttributeError: 'NMF' object has no attribute 'perplexity'

In [29]:
from gensim.models import CoherenceModel
import gensim.corpora as corpora

def get_Cv(model, df_columnm):
  topics = model.components_

  n_top_words = 20
  texts = [[word for word in doc.split()] for doc in df_columnm]

  # create the dictionary
  dictionary = corpora.Dictionary(texts)
  # Create a gensim dictionary from the word count matrix

  # Create a gensim corpus from the word count matrix
  corpus = [dictionary.doc2bow(text) for text in texts]

  feature_names = [dictionary[i] for i in range(len(dictionary))]

  # Get the top words for each topic from the components_ attribute
  top_words = []
  for topic in topics:
      top_words.append([feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]])

  coherence_model = CoherenceModel(topics=top_words, texts=texts, dictionary=dictionary, coherence='c_v')
  coherence = coherence_model.get_coherence()
  return coherence

cv = get_Cv(nmf_model, comments_list)
print("CS:"cv)





0.41851454570039087


In [1]:
perplexity(X, sub_sampling=False)

NameError: name 'perplexity' is not defined